// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDcJyAw6LLtpwl9Ys9rzBFiHLqwh93680',
    appId: '1:128229674562:web:a72fb7890544a4896e67db',
    messagingSenderId: '128229674562',
    projectId: 'eventlyapp-4b748',
    authDomain: 'eventlyapp-4b748.firebaseapp.com',
    storageBucket: 'eventlyapp-4b748.firebasestorage.app',
    measurementId: 'G-4MGZV0Z085',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARQ7Ro_MhgnMsEksBE9ZMMDyVenziqaI4',
    appId: '1:128229674562:android:39c84bc3ad5edf606e67db',
    messagingSenderId: '128229674562',
    projectId: 'eventlyapp-4b748',
    storageBucket: 'eventlyapp-4b748.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAynfbf3x1y4B2cFysd5dQaeYLbzQYmA3o',
    appId: '1:128229674562:ios:9c55ba9b49d7fd226e67db',
    messagingSenderId: '128229674562',
    projectId: 'eventlyapp-4b748',
    storageBucket: 'eventlyapp-4b748.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAynfbf3x1y4B2cFysd5dQaeYLbzQYmA3o',
    appId: '1:128229674562:ios:9c55ba9b49d7fd226e67db',
    messagingSenderId: '128229674562',
    projectId: 'eventlyapp-4b748',
    storageBucket: 'eventlyapp-4b748.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDcJyAw6LLtpwl9Ys9rzBFiHLqwh93680',
    appId: '1:128229674562:web:f3509a94308c4f176e67db',
    messagingSenderId: '128229674562',
    projectId: 'eventlyapp-4b748',
    authDomain: 'eventlyapp-4b748.firebaseapp.com',
    storageBucket: 'eventlyapp-4b748.firebasestorage.app',
    measurementId: 'G-FVFSZ9KBEF',
  );
}
